<?php

namespace AppBundle\Repository;

/**
 * IdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
