<?php

namespace AppBundle\Repository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends \Doctrine\ORM\EntityRepository
{
}
