<?php

namespace AppBundle\Repository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends \Doctrine\ORM\EntityRepository
{
    public function ofertasEmpresa($id)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT o
                               FROM AppBundle:Oferta o 
                               WHERE :id = o.empresa')
            ->setParameter('id', $id);

        return $result->getResult();
    }

    public function count($id)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT COUNT(o) AS num
                               FROM AppBundle:Oferta o 
                               WHERE :id = o.empresa')
            ->setParameter('id', $id);

        return $result->getResult();
    }

    public function activos($id)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT COUNT(o) AS activo
                               FROM AppBundle:Oferta o 
                               WHERE 1 = o.estado AND :id = o.empresa')
            ->setParameter('id', $id);

        return $result->getResult();
    }
}
