<?php

namespace AppBundle\Repository;

/**
 * Oferta_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Oferta_infoRepository extends \Doctrine\ORM\EntityRepository
{
}
