<?php

namespace AppBundle\Repository;

/**
 * Usu_habilidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usu_habilidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
