<?php

namespace AppBundle\Repository;

/**
 * Usu_experiencia_laboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usu_experiencia_laboralRepository extends \Doctrine\ORM\EntityRepository
{
}
