<?php

namespace AppBundle\Repository;

/**
 * Usu_conocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usu_conocimientoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findById($id) {
        $result = $this->getEntityManager()
                       ->createQuery('SELECT c
                                           FROM AppBundle:Usu_conocimiento c 
                                           WHERE :id = c.usuario')
                       ->setParameter('id', $id);

        return $result->getResult();
    }
}
