<?php

namespace AppBundle\Repository;

/**
 * Usu_conocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usu_conocimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
