<?php

namespace AppBundle\Repository;

/**
 * Usuario
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usuario extends \Doctrine\ORM\EntityRepository
{
}
