<?php

namespace AppBundle\Repository;

/**
 * Usuario_idiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usuario_idiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
