<?php

namespace AppBundle\Repository;

/**
 * usuario_ofertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuario_ofertaRepository extends \Doctrine\ORM\EntityRepository
{
}
