index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }

#Login y Registro
login:
    path: /login
    defaults: { _controller: "AppBundle:Security:login" }
    methods: [GET, POST]
registro:
    path: /register
    defaults: { _controller: "AppBundle:Security:registro" }
logout:
    path: /logout
    defaults: { _controller: "AppBundle:Security:logout" }
#Trabajo
lista: 
    path: /list_trabajos
    defaults: { _controller: "AppBundle:Trabajo:list" }

#Datos personales
perfil:
    path: /profile
    defaults: { _controller: "AppBundle:Perfil:perfil" }
perfil-editar:
    path: /editar-usuario
    defaults: { _controller: "AppBundle:Perfil:editarPerfil" }
curriculum:
    path: /profile/curriculum
    defaults: { _controller: "AppBundle:Perfil:curriculum" }

#Rutas conocimientos
addConocimiento:
    path: /curriculum/add_conocimiento
    defaults: { _controller: "AppBundle:Conocimiento:addConocimiento" }
editConocimiento:
    path: /curriculum/edit_conocimiento/{id}
    defaults: { _controller: "AppBundle:Conocimiento:editConocimiento" }
deleteConocimiento:
    path: /curriculum/delete_conocimiento/{id}
    defaults: { _controller: "AppBundle:Conocimiento:deleteConocimiento" }

#Rutas educacion
addEducacion:
    path: /curriculum/add_educacion
    defaults: { _controller: "AppBundle:Educacion:addEducacion" }
editEducacion:
    path: /curriculum/edit_educacion/{id}
    defaults: { _controller: "AppBundle:Educacion:editEducacion" }
deleteEducacion:
    path: /curriculum/delete_educacion/{id}
    defaults: { _controller: "AppBundle:Educacion:deleteEducacion" }

#Rutas experiencia
addExperiencia:
    path: /curriculum/add_experiencia
    defaults: { _controller: "AppBundle:Experiencia:addExperiencia" }
editExperiencia:
    path: /curriculum/edit_experiencia/{id}
    defaults: { _controller: "AppBundle:Experiencia:editExperiencia" }
deleteExperiencia:
    path: /curriculum/remove_experiencia/{id}
    defaults: { _controller: "AppBundle:Experiencia:deleteExperiencia" }

#Rutas idioma
addIdioma:
    path: /curriculum/add_idioma
    defaults: { _controller: "AppBundle:Idioma:addIdioma" }
editIdioma:
    path: /curriculum/edit_idioma/{id}
    defaults: { _controller: "AppBundle:Idioma:editIdioma" }
deleteIdioma:
    path: /curriculum/delete_idioma/{id}
    defaults: { _controller: "AppBundle:Idioma:deleteIdioma" }

#Rutas informacion
addInformacion:
    path: /curriculum/add_informacion
    defaults: { _controller: "AppBundle:Informacion:addInformacion" }
editInformacion:
    path: /curriculum/edit_informacion/{id}
    defaults: { _controller: "AppBundle:Informacion:editInformacion" }

#------------------------ ZONA EMPRESARIO ------------------------
loginEmp:
    path: /empresa/login
    defaults: { _controller: "AppBundle:SecurityEmpresa:login" }