inicio:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
index:
    path: /index
    defaults: { _controller: "AppBundle:Default:index" }
funcionamos:
    path: /como_funcionamos
    defaults: { _controller: "AppBundle:Default:funcionamos" }
nosotros:
    path: /nosotros
    defaults: { _controller: "AppBundle:Default:nosotros" }

#Login y Registro
login:
    path: /usuario/login
    defaults: { _controller: "AppBundle:Security:login" }
    methods: [GET, POST]
registro:
    path: /usuario/register
    defaults: { _controller: "AppBundle:Security:registro" }
logout:
    path: /usuario/logout
    defaults: { _controller: "AppBundle:Security:logout" }
logoutEmp:
    path: /empresa/logout
    defaults: { _controller: "AppBundle:Security:logout" }
#Trabajo
list:
    path: /list_trabajos
    defaults: { _controller: "AppBundle:Trabajo:list" }
lista:
    path: /usuario/list_trabajos
    defaults: { _controller: "AppBundle:Trabajo:list" }
listaEmp:
    path: /empresa/list_trabajos
    defaults: { _controller: "AppBundle:Trabajo:list" }

#Datos personales
perfil:
    path: /usuario/profile
    defaults: { _controller: "AppBundle:Perfil:perfil" }
perfil-editar:
    path: /usuario/editar-usuario
    defaults: { _controller: "AppBundle:Perfil:editarPerfil" }

#Rutas conocimientos
addConocimiento:
    path: /usuario/curriculum/add_conocimiento
    defaults: { _controller: "AppBundle:Conocimiento:addConocimiento" }
editConocimiento:
    path: /usuario/curriculum/edit_conocimiento/{id}
    defaults: { _controller: "AppBundle:Conocimiento:editConocimiento" }
deleteConocimiento:
    path: /usuario/curriculum/delete_conocimiento/{id}
    defaults: { _controller: "AppBundle:Conocimiento:deleteConocimiento" }

#Rutas educacion
addEducacion:
    path: /usuario/curriculum/add_educacion
    defaults: { _controller: "AppBundle:Educacion:addEducacion" }
editEducacion:
    path: /usuario/curriculum/edit_educacion/{id}
    defaults: { _controller: "AppBundle:Educacion:editEducacion" }
deleteEducacion:
    path: /usuario/curriculum/delete_educacion/{id}
    defaults: { _controller: "AppBundle:Educacion:deleteEducacion" }

#Rutas experiencia
addExperiencia:
    path: /usuario/curriculum/add_experiencia
    defaults: { _controller: "AppBundle:Experiencia:addExperiencia" }
editExperiencia:
    path: /usuario/curriculum/edit_experiencia/{id}
    defaults: { _controller: "AppBundle:Experiencia:editExperiencia" }
deleteExperiencia:
    path: /usuario/curriculum/remove_experiencia/{id}
    defaults: { _controller: "AppBundle:Experiencia:deleteExperiencia" }

#Rutas idioma
addIdioma:
    path: /usuario/curriculum/add_idioma
    defaults: { _controller: "AppBundle:Idioma:addIdioma" }
editIdioma:
    path: /usuario/curriculum/edit_idioma/{id}
    defaults: { _controller: "AppBundle:Idioma:editIdioma" }
deleteIdioma:
    path: /usuario/curriculum/delete_idioma/{id}
    defaults: { _controller: "AppBundle:Idioma:deleteIdioma" }

#Rutas informacion
addInformacion:
    path: /usuario/curriculum/add_informacion
    defaults: { _controller: "AppBundle:Informacion:addInformacion" }
editInformacion:
    path: /usuario/curriculum/edit_informacion/{id}
    defaults: { _controller: "AppBundle:Informacion:editInformacion" }

#Rutas conocimientos
addConocimiento:
    path: /usuario/curriculum/edit_conocimiento
    defaults: { _controller: "AppBundle:Conocimiento:editConocimiento" }
editConocimiento:
    path: /usuario/curriculum/add_conocimiento
    defaults: { _controller: "AppBundle:Conocimiento:addConocimiento" }
deleteConocimiento:
    path: /usuario/curriculum/delete_conocimiento
    defaults: { _controller: "AppBundle:Conocimiento:deleteConocimiento" }

#Curriculum Pdf
generatePdf:
    path: /usuario/curriculumPdf
    defaults:  { _controller: "AppBundle:Pdf:generatePdf" }

#------------------------ ZONA EMPRESARIO ------------------------
loginEmp:
    path: /empresa/login
    defaults: { _controller: "AppBundle:SecurityEmpresa:login" }
registroEmp:
    path: /empresa/registro
    defaults: { _controller: "AppBundle:SecurityEmpresa:registro" }
ofertasEmp:
    path: /empresa/ofertas
    defaults: {_controller: "AppBundle:OfertasEmpresa:ofertaEmpresa" }
addOferta:
    path: /empresa/nuevaOferta
    defaults: {_controller: "AppBundle:OfertasEmpresa:addOferta" }