AppBundle\Entity\Empresa:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EmpresaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        nombre:
            type: string
            length: 255
            unique: true
        alias:
            type: string
            length: 255
            unique: true
        municipio:
            type: string
            length: 255
        codigoPostal:
            type: integer
            column: codigo_postal
        direccion:
            type: string
            length: 255
        telefono:
            type: integer
        fax:
            type: integer
        web:
            type: string
            length: 255
        imagen:
            type: string
            length: 255
        descripcion:
            type: text
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        google:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
        linkedin:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        provincias:
            targetEntity: Provincias
            inversedBy: empresa
            joinColumn:
                name: id_provincia
                referencedColumnName: id
        paises:
            targetEntity: Paises
            inversedBy: empresa
            joinColumn:
                name: id_paises
                referencedColumnName: id

    manyToMany:
        oferta:
            targetEntity: Oferta
            inversedBy: empresa
            joinTable:
                name: empresa_oferta
                joinColumns:
                    id_empresa:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                inverseJoinColumns:
                    id_oferta:
                        referencedColumnName: id
                        columnDefinition: INT NULL