AppBundle\Entity\Idioma:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\IdiomaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idioma:
            type: string
            length: '30'
    lifecycleCallbacks: {  }

    oneToMany:
        usuIdioma:
            targetEntity: Usu_idioma
            mappedBy: idiomas