AppBundle\Entity\Paises:
    type: entity
    table: paises
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
    lifecycleCallbacks: {  }

    oneToMany:
        usuario:
            targetEntity: Usuario
            mappedBy: paises