AppBundle\Entity\Usu_idioma:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Usu_idiomaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lenguaje:
            type: string
            length: 255
        nivel:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
