AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    repositoryClass: AppBundle\Repository\Usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        fechaNacimiento:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: fecha_nacimiento
        sexo:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        paisOrigen:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        provincia:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        codPostal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cod_postal
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telefono:
            type: integer
            nullable: false
            options:
                unsigned: false
        especialidad:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }

    #educacion
    oneToMany:
        educacion:
            targetEntity: Usu_educacion
            mappedBy: usuario
    #experiencia
    oneToMany:
        experiencia:
            targetEntity: Usu_experiencia_laboral
            mappedBy: usuario
    #habilidades
    oneToMany:
        habilidades:
            targetEntity: Usu_habilidades
            mappedBy: usuario
    #informacion
    oneToMany:
        informacion:
            targetEntity: Usu_informacion
            mappedBy: usuario
    #idioma
    oneToMany:
        idioma:
            targetEntity: Usuario_idioma
            mappedBy: usuario