AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    repositoryClass: AppBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        fechaNacimiento:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: fecha_nacimiento
        sexo:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        codPostal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: cod_postal
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telefono:
            type: integer
            nullable: false
            options:
                unsigned: false
        especialidad:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }

    ############## Relaciones ##############

    #Idiomas
    oneToMany:
        idioma:
            targetEntity: Usu_idioma
            mappedBy: usuario

    #educacion
        educacion:
            targetEntity: Usu_educacion
            mappedBy: usuario

    #experiencia_laboral
        experiencia:
            targetEntity: Usu_exp_laboral
            mappedBy: usuario

    #informacion
        informacion:
            targetEntity: Usu_informacion
            mappedBy: usuario

    #conocimiento
        conocimiento:
            targetEntity: Usu_conocimiento
            mappedBy: usuario

    manyToOne:
        provincias:
            targetEntity: Provincias
            inversedBy: usuario
            joinColumn:
                name: id_provincia
                referencedColumnName: id
        paises:
            targetEntity: Paises
            inversedBy: usuario
            joinColumn:
                name: id_paises
                referencedColumnName: id

    oneToMany:
            usuOferta:
              targetEntity: usuario_oferta
              mappedBy: usuario