AppBundle\Entity\Usuario_idioma:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Usuario_idiomaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUsuario:
            type: integer
            column: id_usuario
        idIdioma:
            type: integer
            column: id_idioma
        conocimiento:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToOne:
        usuario:
            targetEntity: Usuario
            inversedBy: idioma
            joinColumn:
                name: id_usuario
                referencedColumnName: id
        idioma:
              targetEntity: Usu_idioma
              inversedBy: idioma
              joinColumn:
                  name: id_idioma
                  referencedColumnName: id