# config/validator/validation.yml
App\Entity\Usuario:
    properties:
        password:
            Regex:
                pattern: '/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/'
                match:   false
                message: La contraseña debe contener mínimo 8 caracteres y al menos una letra y un número
        email:
            Regex:
                pattern: '/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/'
                match:   false
                message: El email es incorrecto
        fechaNacimiento:
            Regex:
                pattern: '/^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]|(?:Jan|Mar|May|Jul|Aug|Oct|Dec)))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2]|(?:Jan|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)(?:0?2|(?:Feb))\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9]|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep))|(?:1[0-2]|(?:Oct|Nov|Dec)))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$/'
                match:   false
                message: La fecha de nacimiento es incorrecta
        codPostal:
            Regex:
                pattern: '/^(?:0[1-9]|[1-4]\d|5[0-2])\d{3}$/'
                match:   false
                message: El código postal es incorrecto
        telefono:
            Regex:
                pattern: '  /^[9|6|7][0-9]{8}$//'
                match:   false
                message: El teléfono es incorrecto
